/*
Zinc Search engine API

Zinc Search engine API documents https://zincsearch-docs.zinc.dev

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AuthLoginRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthLoginRequest{}

// AuthLoginRequest struct for AuthLoginRequest
type AuthLoginRequest struct {
	Id       *string `json:"_id,omitempty"`
	Password *string `json:"password,omitempty"`
}

// NewAuthLoginRequest instantiates a new AuthLoginRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthLoginRequest() *AuthLoginRequest {
	this := AuthLoginRequest{}
	return &this
}

// NewAuthLoginRequestWithDefaults instantiates a new AuthLoginRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthLoginRequestWithDefaults() *AuthLoginRequest {
	this := AuthLoginRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AuthLoginRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthLoginRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AuthLoginRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AuthLoginRequest) SetId(v string) {
	o.Id = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *AuthLoginRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthLoginRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *AuthLoginRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *AuthLoginRequest) SetPassword(v string) {
	o.Password = &v
}

func (o AuthLoginRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthLoginRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["_id"] = o.Id
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableAuthLoginRequest struct {
	value *AuthLoginRequest
	isSet bool
}

func (v NullableAuthLoginRequest) Get() *AuthLoginRequest {
	return v.value
}

func (v *NullableAuthLoginRequest) Set(val *AuthLoginRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthLoginRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthLoginRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthLoginRequest(val *AuthLoginRequest) *NullableAuthLoginRequest {
	return &NullableAuthLoginRequest{value: val, isSet: true}
}

func (v NullableAuthLoginRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthLoginRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
