/*
Zinc Search engine API

Zinc Search engine API documents https://zincsearch-docs.zinc.dev

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MetaHits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetaHits{}

// MetaHits struct for MetaHits
type MetaHits struct {
	Hits     []MetaHit  `json:"hits,omitempty"`
	MaxScore *float32   `json:"max_score,omitempty"`
	Total    *MetaTotal `json:"total,omitempty"`
}

// NewMetaHits instantiates a new MetaHits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaHits() *MetaHits {
	this := MetaHits{}
	return &this
}

// NewMetaHitsWithDefaults instantiates a new MetaHits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaHitsWithDefaults() *MetaHits {
	this := MetaHits{}
	return &this
}

// GetHits returns the Hits field value if set, zero value otherwise.
func (o *MetaHits) GetHits() []MetaHit {
	if o == nil || IsNil(o.Hits) {
		var ret []MetaHit
		return ret
	}
	return o.Hits
}

// GetHitsOk returns a tuple with the Hits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaHits) GetHitsOk() ([]MetaHit, bool) {
	if o == nil || IsNil(o.Hits) {
		return nil, false
	}
	return o.Hits, true
}

// HasHits returns a boolean if a field has been set.
func (o *MetaHits) HasHits() bool {
	if o != nil && !IsNil(o.Hits) {
		return true
	}

	return false
}

// SetHits gets a reference to the given []MetaHit and assigns it to the Hits field.
func (o *MetaHits) SetHits(v []MetaHit) {
	o.Hits = v
}

// GetMaxScore returns the MaxScore field value if set, zero value otherwise.
func (o *MetaHits) GetMaxScore() float32 {
	if o == nil || IsNil(o.MaxScore) {
		var ret float32
		return ret
	}
	return *o.MaxScore
}

// GetMaxScoreOk returns a tuple with the MaxScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaHits) GetMaxScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxScore) {
		return nil, false
	}
	return o.MaxScore, true
}

// HasMaxScore returns a boolean if a field has been set.
func (o *MetaHits) HasMaxScore() bool {
	if o != nil && !IsNil(o.MaxScore) {
		return true
	}

	return false
}

// SetMaxScore gets a reference to the given float32 and assigns it to the MaxScore field.
func (o *MetaHits) SetMaxScore(v float32) {
	o.MaxScore = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *MetaHits) GetTotal() MetaTotal {
	if o == nil || IsNil(o.Total) {
		var ret MetaTotal
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaHits) GetTotalOk() (*MetaTotal, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *MetaHits) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given MetaTotal and assigns it to the Total field.
func (o *MetaHits) SetTotal(v MetaTotal) {
	o.Total = &v
}

func (o MetaHits) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetaHits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hits) {
		toSerialize["hits"] = o.Hits
	}
	if !IsNil(o.MaxScore) {
		toSerialize["max_score"] = o.MaxScore
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableMetaHits struct {
	value *MetaHits
	isSet bool
}

func (v NullableMetaHits) Get() *MetaHits {
	return v.value
}

func (v *NullableMetaHits) Set(val *MetaHits) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaHits) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaHits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaHits(val *MetaHits) *NullableMetaHits {
	return &NullableMetaHits{value: val, isSet: true}
}

func (v NullableMetaHits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaHits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
