/*
Zinc Search engine API

Zinc Search engine API documents https://zincsearch-docs.zinc.dev

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MetaAggregationDateRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetaAggregationDateRange{}

// MetaAggregationDateRange struct for MetaAggregationDateRange
type MetaAggregationDateRange struct {
	Field *string `json:"field,omitempty"`
	// format the `to` and `from` values to `_as_string`, and used to format `keyed response`
	Format *string `json:"format,omitempty"`
	Keyed  *bool   `json:"keyed,omitempty"`
	// refer
	Ranges []MetaDateRange `json:"ranges,omitempty"`
	// refer
	TimeZone *string `json:"time_zone,omitempty"`
}

// NewMetaAggregationDateRange instantiates a new MetaAggregationDateRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaAggregationDateRange() *MetaAggregationDateRange {
	this := MetaAggregationDateRange{}
	return &this
}

// NewMetaAggregationDateRangeWithDefaults instantiates a new MetaAggregationDateRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaAggregationDateRangeWithDefaults() *MetaAggregationDateRange {
	this := MetaAggregationDateRange{}
	return &this
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *MetaAggregationDateRange) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaAggregationDateRange) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *MetaAggregationDateRange) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *MetaAggregationDateRange) SetField(v string) {
	o.Field = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *MetaAggregationDateRange) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaAggregationDateRange) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *MetaAggregationDateRange) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *MetaAggregationDateRange) SetFormat(v string) {
	o.Format = &v
}

// GetKeyed returns the Keyed field value if set, zero value otherwise.
func (o *MetaAggregationDateRange) GetKeyed() bool {
	if o == nil || IsNil(o.Keyed) {
		var ret bool
		return ret
	}
	return *o.Keyed
}

// GetKeyedOk returns a tuple with the Keyed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaAggregationDateRange) GetKeyedOk() (*bool, bool) {
	if o == nil || IsNil(o.Keyed) {
		return nil, false
	}
	return o.Keyed, true
}

// HasKeyed returns a boolean if a field has been set.
func (o *MetaAggregationDateRange) HasKeyed() bool {
	if o != nil && !IsNil(o.Keyed) {
		return true
	}

	return false
}

// SetKeyed gets a reference to the given bool and assigns it to the Keyed field.
func (o *MetaAggregationDateRange) SetKeyed(v bool) {
	o.Keyed = &v
}

// GetRanges returns the Ranges field value if set, zero value otherwise.
func (o *MetaAggregationDateRange) GetRanges() []MetaDateRange {
	if o == nil || IsNil(o.Ranges) {
		var ret []MetaDateRange
		return ret
	}
	return o.Ranges
}

// GetRangesOk returns a tuple with the Ranges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaAggregationDateRange) GetRangesOk() ([]MetaDateRange, bool) {
	if o == nil || IsNil(o.Ranges) {
		return nil, false
	}
	return o.Ranges, true
}

// HasRanges returns a boolean if a field has been set.
func (o *MetaAggregationDateRange) HasRanges() bool {
	if o != nil && !IsNil(o.Ranges) {
		return true
	}

	return false
}

// SetRanges gets a reference to the given []MetaDateRange and assigns it to the Ranges field.
func (o *MetaAggregationDateRange) SetRanges(v []MetaDateRange) {
	o.Ranges = v
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise.
func (o *MetaAggregationDateRange) GetTimeZone() string {
	if o == nil || IsNil(o.TimeZone) {
		var ret string
		return ret
	}
	return *o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaAggregationDateRange) GetTimeZoneOk() (*string, bool) {
	if o == nil || IsNil(o.TimeZone) {
		return nil, false
	}
	return o.TimeZone, true
}

// HasTimeZone returns a boolean if a field has been set.
func (o *MetaAggregationDateRange) HasTimeZone() bool {
	if o != nil && !IsNil(o.TimeZone) {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given string and assigns it to the TimeZone field.
func (o *MetaAggregationDateRange) SetTimeZone(v string) {
	o.TimeZone = &v
}

func (o MetaAggregationDateRange) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetaAggregationDateRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.Keyed) {
		toSerialize["keyed"] = o.Keyed
	}
	if !IsNil(o.Ranges) {
		toSerialize["ranges"] = o.Ranges
	}
	if !IsNil(o.TimeZone) {
		toSerialize["time_zone"] = o.TimeZone
	}
	return toSerialize, nil
}

type NullableMetaAggregationDateRange struct {
	value *MetaAggregationDateRange
	isSet bool
}

func (v NullableMetaAggregationDateRange) Get() *MetaAggregationDateRange {
	return v.value
}

func (v *NullableMetaAggregationDateRange) Set(val *MetaAggregationDateRange) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaAggregationDateRange) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaAggregationDateRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaAggregationDateRange(val *MetaAggregationDateRange) *NullableMetaAggregationDateRange {
	return &NullableMetaAggregationDateRange{value: val, isSet: true}
}

func (v NullableMetaAggregationDateRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaAggregationDateRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
