/*
Zinc Search engine API

Zinc Search engine API documents https://zincsearch-docs.zinc.dev

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MetaIndexSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetaIndexSettings{}

// MetaIndexSettings struct for MetaIndexSettings
type MetaIndexSettings struct {
	Analysis         *MetaIndexAnalysis `json:"analysis,omitempty"`
	NumberOfReplicas *int32             `json:"number_of_replicas,omitempty"`
	NumberOfShards   *int32             `json:"number_of_shards,omitempty"`
}

// NewMetaIndexSettings instantiates a new MetaIndexSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaIndexSettings() *MetaIndexSettings {
	this := MetaIndexSettings{}
	return &this
}

// NewMetaIndexSettingsWithDefaults instantiates a new MetaIndexSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaIndexSettingsWithDefaults() *MetaIndexSettings {
	this := MetaIndexSettings{}
	return &this
}

// GetAnalysis returns the Analysis field value if set, zero value otherwise.
func (o *MetaIndexSettings) GetAnalysis() MetaIndexAnalysis {
	if o == nil || IsNil(o.Analysis) {
		var ret MetaIndexAnalysis
		return ret
	}
	return *o.Analysis
}

// GetAnalysisOk returns a tuple with the Analysis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaIndexSettings) GetAnalysisOk() (*MetaIndexAnalysis, bool) {
	if o == nil || IsNil(o.Analysis) {
		return nil, false
	}
	return o.Analysis, true
}

// HasAnalysis returns a boolean if a field has been set.
func (o *MetaIndexSettings) HasAnalysis() bool {
	if o != nil && !IsNil(o.Analysis) {
		return true
	}

	return false
}

// SetAnalysis gets a reference to the given MetaIndexAnalysis and assigns it to the Analysis field.
func (o *MetaIndexSettings) SetAnalysis(v MetaIndexAnalysis) {
	o.Analysis = &v
}

// GetNumberOfReplicas returns the NumberOfReplicas field value if set, zero value otherwise.
func (o *MetaIndexSettings) GetNumberOfReplicas() int32 {
	if o == nil || IsNil(o.NumberOfReplicas) {
		var ret int32
		return ret
	}
	return *o.NumberOfReplicas
}

// GetNumberOfReplicasOk returns a tuple with the NumberOfReplicas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaIndexSettings) GetNumberOfReplicasOk() (*int32, bool) {
	if o == nil || IsNil(o.NumberOfReplicas) {
		return nil, false
	}
	return o.NumberOfReplicas, true
}

// HasNumberOfReplicas returns a boolean if a field has been set.
func (o *MetaIndexSettings) HasNumberOfReplicas() bool {
	if o != nil && !IsNil(o.NumberOfReplicas) {
		return true
	}

	return false
}

// SetNumberOfReplicas gets a reference to the given int32 and assigns it to the NumberOfReplicas field.
func (o *MetaIndexSettings) SetNumberOfReplicas(v int32) {
	o.NumberOfReplicas = &v
}

// GetNumberOfShards returns the NumberOfShards field value if set, zero value otherwise.
func (o *MetaIndexSettings) GetNumberOfShards() int32 {
	if o == nil || IsNil(o.NumberOfShards) {
		var ret int32
		return ret
	}
	return *o.NumberOfShards
}

// GetNumberOfShardsOk returns a tuple with the NumberOfShards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaIndexSettings) GetNumberOfShardsOk() (*int32, bool) {
	if o == nil || IsNil(o.NumberOfShards) {
		return nil, false
	}
	return o.NumberOfShards, true
}

// HasNumberOfShards returns a boolean if a field has been set.
func (o *MetaIndexSettings) HasNumberOfShards() bool {
	if o != nil && !IsNil(o.NumberOfShards) {
		return true
	}

	return false
}

// SetNumberOfShards gets a reference to the given int32 and assigns it to the NumberOfShards field.
func (o *MetaIndexSettings) SetNumberOfShards(v int32) {
	o.NumberOfShards = &v
}

func (o MetaIndexSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetaIndexSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Analysis) {
		toSerialize["analysis"] = o.Analysis
	}
	if !IsNil(o.NumberOfReplicas) {
		toSerialize["number_of_replicas"] = o.NumberOfReplicas
	}
	if !IsNil(o.NumberOfShards) {
		toSerialize["number_of_shards"] = o.NumberOfShards
	}
	return toSerialize, nil
}

type NullableMetaIndexSettings struct {
	value *MetaIndexSettings
	isSet bool
}

func (v NullableMetaIndexSettings) Get() *MetaIndexSettings {
	return v.value
}

func (v *NullableMetaIndexSettings) Set(val *MetaIndexSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaIndexSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaIndexSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaIndexSettings(val *MetaIndexSettings) *NullableMetaIndexSettings {
	return &NullableMetaIndexSettings{value: val, isSet: true}
}

func (v NullableMetaIndexSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaIndexSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
