/*
Zinc Search engine API

Zinc Search engine API documents https://zincsearch-docs.zinc.dev

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MetaTotal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetaTotal{}

// MetaTotal struct for MetaTotal
type MetaTotal struct {
	// Count of documents returned
	Value *int32 `json:"value,omitempty"`
}

// NewMetaTotal instantiates a new MetaTotal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaTotal() *MetaTotal {
	this := MetaTotal{}
	return &this
}

// NewMetaTotalWithDefaults instantiates a new MetaTotal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaTotalWithDefaults() *MetaTotal {
	this := MetaTotal{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *MetaTotal) GetValue() int32 {
	if o == nil || IsNil(o.Value) {
		var ret int32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaTotal) GetValueOk() (*int32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *MetaTotal) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given int32 and assigns it to the Value field.
func (o *MetaTotal) SetValue(v int32) {
	o.Value = &v
}

func (o MetaTotal) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetaTotal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableMetaTotal struct {
	value *MetaTotal
	isSet bool
}

func (v NullableMetaTotal) Get() *MetaTotal {
	return v.value
}

func (v *NullableMetaTotal) Set(val *MetaTotal) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaTotal) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaTotal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaTotal(val *MetaTotal) *NullableMetaTotal {
	return &NullableMetaTotal{value: val, isSet: true}
}

func (v NullableMetaTotal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaTotal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
