/*
Zinc Search engine API

Zinc Search engine API documents https://zincsearch-docs.zinc.dev

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MetaHTTPResponseID type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetaHTTPResponseID{}

// MetaHTTPResponseID struct for MetaHTTPResponseID
type MetaHTTPResponseID struct {
	Id      *string `json:"id,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewMetaHTTPResponseID instantiates a new MetaHTTPResponseID object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaHTTPResponseID() *MetaHTTPResponseID {
	this := MetaHTTPResponseID{}
	return &this
}

// NewMetaHTTPResponseIDWithDefaults instantiates a new MetaHTTPResponseID object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaHTTPResponseIDWithDefaults() *MetaHTTPResponseID {
	this := MetaHTTPResponseID{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MetaHTTPResponseID) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaHTTPResponseID) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MetaHTTPResponseID) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MetaHTTPResponseID) SetId(v string) {
	o.Id = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *MetaHTTPResponseID) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaHTTPResponseID) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *MetaHTTPResponseID) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *MetaHTTPResponseID) SetMessage(v string) {
	o.Message = &v
}

func (o MetaHTTPResponseID) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetaHTTPResponseID) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableMetaHTTPResponseID struct {
	value *MetaHTTPResponseID
	isSet bool
}

func (v NullableMetaHTTPResponseID) Get() *MetaHTTPResponseID {
	return v.value
}

func (v *NullableMetaHTTPResponseID) Set(val *MetaHTTPResponseID) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaHTTPResponseID) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaHTTPResponseID) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaHTTPResponseID(val *MetaHTTPResponseID) *NullableMetaHTTPResponseID {
	return &NullableMetaHTTPResponseID{value: val, isSet: true}
}

func (v NullableMetaHTTPResponseID) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaHTTPResponseID) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
