/*
Zinc Search engine API

Zinc Search engine API documents https://zincsearch-docs.zinc.dev

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MetaHTTPResponseTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetaHTTPResponseTemplate{}

// MetaHTTPResponseTemplate struct for MetaHTTPResponseTemplate
type MetaHTTPResponseTemplate struct {
	Message  *string `json:"message,omitempty"`
	Template *string `json:"template,omitempty"`
}

// NewMetaHTTPResponseTemplate instantiates a new MetaHTTPResponseTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaHTTPResponseTemplate() *MetaHTTPResponseTemplate {
	this := MetaHTTPResponseTemplate{}
	return &this
}

// NewMetaHTTPResponseTemplateWithDefaults instantiates a new MetaHTTPResponseTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaHTTPResponseTemplateWithDefaults() *MetaHTTPResponseTemplate {
	this := MetaHTTPResponseTemplate{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *MetaHTTPResponseTemplate) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaHTTPResponseTemplate) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *MetaHTTPResponseTemplate) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *MetaHTTPResponseTemplate) SetMessage(v string) {
	o.Message = &v
}

// GetTemplate returns the Template field value if set, zero value otherwise.
func (o *MetaHTTPResponseTemplate) GetTemplate() string {
	if o == nil || IsNil(o.Template) {
		var ret string
		return ret
	}
	return *o.Template
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaHTTPResponseTemplate) GetTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.Template) {
		return nil, false
	}
	return o.Template, true
}

// HasTemplate returns a boolean if a field has been set.
func (o *MetaHTTPResponseTemplate) HasTemplate() bool {
	if o != nil && !IsNil(o.Template) {
		return true
	}

	return false
}

// SetTemplate gets a reference to the given string and assigns it to the Template field.
func (o *MetaHTTPResponseTemplate) SetTemplate(v string) {
	o.Template = &v
}

func (o MetaHTTPResponseTemplate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetaHTTPResponseTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Template) {
		toSerialize["template"] = o.Template
	}
	return toSerialize, nil
}

type NullableMetaHTTPResponseTemplate struct {
	value *MetaHTTPResponseTemplate
	isSet bool
}

func (v NullableMetaHTTPResponseTemplate) Get() *MetaHTTPResponseTemplate {
	return v.value
}

func (v *NullableMetaHTTPResponseTemplate) Set(val *MetaHTTPResponseTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaHTTPResponseTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaHTTPResponseTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaHTTPResponseTemplate(val *MetaHTTPResponseTemplate) *NullableMetaHTTPResponseTemplate {
	return &NullableMetaHTTPResponseTemplate{value: val, isSet: true}
}

func (v NullableMetaHTTPResponseTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaHTTPResponseTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
