/*
Zinc Search engine API

Zinc Search engine API documents https://zincsearch-docs.zinc.dev

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MetaZincQueryForSDK type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetaZincQueryForSDK{}

// MetaZincQueryForSDK struct for MetaZincQueryForSDK
type MetaZincQueryForSDK struct {
	// true, false, [\"field1\", \"field2.*\"]
	Source  []string                     `json:"_source,omitempty"`
	Aggs    *map[string]MetaAggregations `json:"aggs,omitempty"`
	Explain *bool                        `json:"explain,omitempty"`
	// [\"field1\", \"field2.*\", {\"field\": \"fieldName\", \"format\": \"epoch_millis\"}]
	Fields    []string         `json:"fields,omitempty"`
	From      *int32           `json:"from,omitempty"`
	Highlight *MetaHighlight   `json:"highlight,omitempty"`
	Query     *MetaQueryForSDK `json:"query,omitempty"`
	Size      *int32           `json:"size,omitempty"`
	// \"_score\", [\"+Year\",\"-Year\", {\"Year\": \"desc\"}, \"Date\": {\"order\": \"asc\"\", \"format\": \"yyyy-MM-dd\"}}\"}]
	Sort           []string `json:"sort,omitempty"`
	Timeout        *int32   `json:"timeout,omitempty"`
	TrackTotalHits *bool    `json:"track_total_hits,omitempty"`
}

// NewMetaZincQueryForSDK instantiates a new MetaZincQueryForSDK object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaZincQueryForSDK() *MetaZincQueryForSDK {
	this := MetaZincQueryForSDK{}
	return &this
}

// NewMetaZincQueryForSDKWithDefaults instantiates a new MetaZincQueryForSDK object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaZincQueryForSDKWithDefaults() *MetaZincQueryForSDK {
	this := MetaZincQueryForSDK{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *MetaZincQueryForSDK) GetSource() []string {
	if o == nil || IsNil(o.Source) {
		var ret []string
		return ret
	}
	return o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaZincQueryForSDK) GetSourceOk() ([]string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *MetaZincQueryForSDK) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given []string and assigns it to the Source field.
func (o *MetaZincQueryForSDK) SetSource(v []string) {
	o.Source = v
}

// GetAggs returns the Aggs field value if set, zero value otherwise.
func (o *MetaZincQueryForSDK) GetAggs() map[string]MetaAggregations {
	if o == nil || IsNil(o.Aggs) {
		var ret map[string]MetaAggregations
		return ret
	}
	return *o.Aggs
}

// GetAggsOk returns a tuple with the Aggs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaZincQueryForSDK) GetAggsOk() (*map[string]MetaAggregations, bool) {
	if o == nil || IsNil(o.Aggs) {
		return nil, false
	}
	return o.Aggs, true
}

// HasAggs returns a boolean if a field has been set.
func (o *MetaZincQueryForSDK) HasAggs() bool {
	if o != nil && !IsNil(o.Aggs) {
		return true
	}

	return false
}

// SetAggs gets a reference to the given map[string]MetaAggregations and assigns it to the Aggs field.
func (o *MetaZincQueryForSDK) SetAggs(v map[string]MetaAggregations) {
	o.Aggs = &v
}

// GetExplain returns the Explain field value if set, zero value otherwise.
func (o *MetaZincQueryForSDK) GetExplain() bool {
	if o == nil || IsNil(o.Explain) {
		var ret bool
		return ret
	}
	return *o.Explain
}

// GetExplainOk returns a tuple with the Explain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaZincQueryForSDK) GetExplainOk() (*bool, bool) {
	if o == nil || IsNil(o.Explain) {
		return nil, false
	}
	return o.Explain, true
}

// HasExplain returns a boolean if a field has been set.
func (o *MetaZincQueryForSDK) HasExplain() bool {
	if o != nil && !IsNil(o.Explain) {
		return true
	}

	return false
}

// SetExplain gets a reference to the given bool and assigns it to the Explain field.
func (o *MetaZincQueryForSDK) SetExplain(v bool) {
	o.Explain = &v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *MetaZincQueryForSDK) GetFields() []string {
	if o == nil || IsNil(o.Fields) {
		var ret []string
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaZincQueryForSDK) GetFieldsOk() ([]string, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *MetaZincQueryForSDK) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []string and assigns it to the Fields field.
func (o *MetaZincQueryForSDK) SetFields(v []string) {
	o.Fields = v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *MetaZincQueryForSDK) GetFrom() int32 {
	if o == nil || IsNil(o.From) {
		var ret int32
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaZincQueryForSDK) GetFromOk() (*int32, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *MetaZincQueryForSDK) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given int32 and assigns it to the From field.
func (o *MetaZincQueryForSDK) SetFrom(v int32) {
	o.From = &v
}

// GetHighlight returns the Highlight field value if set, zero value otherwise.
func (o *MetaZincQueryForSDK) GetHighlight() MetaHighlight {
	if o == nil || IsNil(o.Highlight) {
		var ret MetaHighlight
		return ret
	}
	return *o.Highlight
}

// GetHighlightOk returns a tuple with the Highlight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaZincQueryForSDK) GetHighlightOk() (*MetaHighlight, bool) {
	if o == nil || IsNil(o.Highlight) {
		return nil, false
	}
	return o.Highlight, true
}

// HasHighlight returns a boolean if a field has been set.
func (o *MetaZincQueryForSDK) HasHighlight() bool {
	if o != nil && !IsNil(o.Highlight) {
		return true
	}

	return false
}

// SetHighlight gets a reference to the given MetaHighlight and assigns it to the Highlight field.
func (o *MetaZincQueryForSDK) SetHighlight(v MetaHighlight) {
	o.Highlight = &v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *MetaZincQueryForSDK) GetQuery() MetaQueryForSDK {
	if o == nil || IsNil(o.Query) {
		var ret MetaQueryForSDK
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaZincQueryForSDK) GetQueryOk() (*MetaQueryForSDK, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *MetaZincQueryForSDK) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given MetaQueryForSDK and assigns it to the Query field.
func (o *MetaZincQueryForSDK) SetQuery(v MetaQueryForSDK) {
	o.Query = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *MetaZincQueryForSDK) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaZincQueryForSDK) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *MetaZincQueryForSDK) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *MetaZincQueryForSDK) SetSize(v int32) {
	o.Size = &v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *MetaZincQueryForSDK) GetSort() []string {
	if o == nil || IsNil(o.Sort) {
		var ret []string
		return ret
	}
	return o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaZincQueryForSDK) GetSortOk() ([]string, bool) {
	if o == nil || IsNil(o.Sort) {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *MetaZincQueryForSDK) HasSort() bool {
	if o != nil && !IsNil(o.Sort) {
		return true
	}

	return false
}

// SetSort gets a reference to the given []string and assigns it to the Sort field.
func (o *MetaZincQueryForSDK) SetSort(v []string) {
	o.Sort = v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *MetaZincQueryForSDK) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout) {
		var ret int32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaZincQueryForSDK) GetTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *MetaZincQueryForSDK) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int32 and assigns it to the Timeout field.
func (o *MetaZincQueryForSDK) SetTimeout(v int32) {
	o.Timeout = &v
}

// GetTrackTotalHits returns the TrackTotalHits field value if set, zero value otherwise.
func (o *MetaZincQueryForSDK) GetTrackTotalHits() bool {
	if o == nil || IsNil(o.TrackTotalHits) {
		var ret bool
		return ret
	}
	return *o.TrackTotalHits
}

// GetTrackTotalHitsOk returns a tuple with the TrackTotalHits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaZincQueryForSDK) GetTrackTotalHitsOk() (*bool, bool) {
	if o == nil || IsNil(o.TrackTotalHits) {
		return nil, false
	}
	return o.TrackTotalHits, true
}

// HasTrackTotalHits returns a boolean if a field has been set.
func (o *MetaZincQueryForSDK) HasTrackTotalHits() bool {
	if o != nil && !IsNil(o.TrackTotalHits) {
		return true
	}

	return false
}

// SetTrackTotalHits gets a reference to the given bool and assigns it to the TrackTotalHits field.
func (o *MetaZincQueryForSDK) SetTrackTotalHits(v bool) {
	o.TrackTotalHits = &v
}

func (o MetaZincQueryForSDK) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetaZincQueryForSDK) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["_source"] = o.Source
	}
	if !IsNil(o.Aggs) {
		toSerialize["aggs"] = o.Aggs
	}
	if !IsNil(o.Explain) {
		toSerialize["explain"] = o.Explain
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.Highlight) {
		toSerialize["highlight"] = o.Highlight
	}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Sort) {
		toSerialize["sort"] = o.Sort
	}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	if !IsNil(o.TrackTotalHits) {
		toSerialize["track_total_hits"] = o.TrackTotalHits
	}
	return toSerialize, nil
}

type NullableMetaZincQueryForSDK struct {
	value *MetaZincQueryForSDK
	isSet bool
}

func (v NullableMetaZincQueryForSDK) Get() *MetaZincQueryForSDK {
	return v.value
}

func (v *NullableMetaZincQueryForSDK) Set(val *MetaZincQueryForSDK) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaZincQueryForSDK) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaZincQueryForSDK) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaZincQueryForSDK(val *MetaZincQueryForSDK) *NullableMetaZincQueryForSDK {
	return &NullableMetaZincQueryForSDK{value: val, isSet: true}
}

func (v NullableMetaZincQueryForSDK) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaZincQueryForSDK) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
