/*
Zinc Search engine API

Zinc Search engine API documents https://zincsearch-docs.zinc.dev

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MetaRangeQueryForSDK type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetaRangeQueryForSDK{}

// MetaRangeQueryForSDK struct for MetaRangeQueryForSDK
type MetaRangeQueryForSDK struct {
	Boost *float32 `json:"boost,omitempty"`
	// Date format used to convert date values in the query.
	Format *string `json:"format,omitempty"`
	// string, float64
	Gt *string `json:"gt,omitempty"`
	// string, float64
	Gte *string `json:"gte,omitempty"`
	// string, float64
	Lt *string `json:"lt,omitempty"`
	// string, float64
	Lte *string `json:"lte,omitempty"`
	// used to convert date values in the query to UTC.
	TimeZone *string `json:"time_zone,omitempty"`
}

// NewMetaRangeQueryForSDK instantiates a new MetaRangeQueryForSDK object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaRangeQueryForSDK() *MetaRangeQueryForSDK {
	this := MetaRangeQueryForSDK{}
	return &this
}

// NewMetaRangeQueryForSDKWithDefaults instantiates a new MetaRangeQueryForSDK object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaRangeQueryForSDKWithDefaults() *MetaRangeQueryForSDK {
	this := MetaRangeQueryForSDK{}
	return &this
}

// GetBoost returns the Boost field value if set, zero value otherwise.
func (o *MetaRangeQueryForSDK) GetBoost() float32 {
	if o == nil || IsNil(o.Boost) {
		var ret float32
		return ret
	}
	return *o.Boost
}

// GetBoostOk returns a tuple with the Boost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaRangeQueryForSDK) GetBoostOk() (*float32, bool) {
	if o == nil || IsNil(o.Boost) {
		return nil, false
	}
	return o.Boost, true
}

// HasBoost returns a boolean if a field has been set.
func (o *MetaRangeQueryForSDK) HasBoost() bool {
	if o != nil && !IsNil(o.Boost) {
		return true
	}

	return false
}

// SetBoost gets a reference to the given float32 and assigns it to the Boost field.
func (o *MetaRangeQueryForSDK) SetBoost(v float32) {
	o.Boost = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *MetaRangeQueryForSDK) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaRangeQueryForSDK) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *MetaRangeQueryForSDK) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *MetaRangeQueryForSDK) SetFormat(v string) {
	o.Format = &v
}

// GetGt returns the Gt field value if set, zero value otherwise.
func (o *MetaRangeQueryForSDK) GetGt() string {
	if o == nil || IsNil(o.Gt) {
		var ret string
		return ret
	}
	return *o.Gt
}

// GetGtOk returns a tuple with the Gt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaRangeQueryForSDK) GetGtOk() (*string, bool) {
	if o == nil || IsNil(o.Gt) {
		return nil, false
	}
	return o.Gt, true
}

// HasGt returns a boolean if a field has been set.
func (o *MetaRangeQueryForSDK) HasGt() bool {
	if o != nil && !IsNil(o.Gt) {
		return true
	}

	return false
}

// SetGt gets a reference to the given string and assigns it to the Gt field.
func (o *MetaRangeQueryForSDK) SetGt(v string) {
	o.Gt = &v
}

// GetGte returns the Gte field value if set, zero value otherwise.
func (o *MetaRangeQueryForSDK) GetGte() string {
	if o == nil || IsNil(o.Gte) {
		var ret string
		return ret
	}
	return *o.Gte
}

// GetGteOk returns a tuple with the Gte field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaRangeQueryForSDK) GetGteOk() (*string, bool) {
	if o == nil || IsNil(o.Gte) {
		return nil, false
	}
	return o.Gte, true
}

// HasGte returns a boolean if a field has been set.
func (o *MetaRangeQueryForSDK) HasGte() bool {
	if o != nil && !IsNil(o.Gte) {
		return true
	}

	return false
}

// SetGte gets a reference to the given string and assigns it to the Gte field.
func (o *MetaRangeQueryForSDK) SetGte(v string) {
	o.Gte = &v
}

// GetLt returns the Lt field value if set, zero value otherwise.
func (o *MetaRangeQueryForSDK) GetLt() string {
	if o == nil || IsNil(o.Lt) {
		var ret string
		return ret
	}
	return *o.Lt
}

// GetLtOk returns a tuple with the Lt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaRangeQueryForSDK) GetLtOk() (*string, bool) {
	if o == nil || IsNil(o.Lt) {
		return nil, false
	}
	return o.Lt, true
}

// HasLt returns a boolean if a field has been set.
func (o *MetaRangeQueryForSDK) HasLt() bool {
	if o != nil && !IsNil(o.Lt) {
		return true
	}

	return false
}

// SetLt gets a reference to the given string and assigns it to the Lt field.
func (o *MetaRangeQueryForSDK) SetLt(v string) {
	o.Lt = &v
}

// GetLte returns the Lte field value if set, zero value otherwise.
func (o *MetaRangeQueryForSDK) GetLte() string {
	if o == nil || IsNil(o.Lte) {
		var ret string
		return ret
	}
	return *o.Lte
}

// GetLteOk returns a tuple with the Lte field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaRangeQueryForSDK) GetLteOk() (*string, bool) {
	if o == nil || IsNil(o.Lte) {
		return nil, false
	}
	return o.Lte, true
}

// HasLte returns a boolean if a field has been set.
func (o *MetaRangeQueryForSDK) HasLte() bool {
	if o != nil && !IsNil(o.Lte) {
		return true
	}

	return false
}

// SetLte gets a reference to the given string and assigns it to the Lte field.
func (o *MetaRangeQueryForSDK) SetLte(v string) {
	o.Lte = &v
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise.
func (o *MetaRangeQueryForSDK) GetTimeZone() string {
	if o == nil || IsNil(o.TimeZone) {
		var ret string
		return ret
	}
	return *o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaRangeQueryForSDK) GetTimeZoneOk() (*string, bool) {
	if o == nil || IsNil(o.TimeZone) {
		return nil, false
	}
	return o.TimeZone, true
}

// HasTimeZone returns a boolean if a field has been set.
func (o *MetaRangeQueryForSDK) HasTimeZone() bool {
	if o != nil && !IsNil(o.TimeZone) {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given string and assigns it to the TimeZone field.
func (o *MetaRangeQueryForSDK) SetTimeZone(v string) {
	o.TimeZone = &v
}

func (o MetaRangeQueryForSDK) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetaRangeQueryForSDK) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Boost) {
		toSerialize["boost"] = o.Boost
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.Gt) {
		toSerialize["gt"] = o.Gt
	}
	if !IsNil(o.Gte) {
		toSerialize["gte"] = o.Gte
	}
	if !IsNil(o.Lt) {
		toSerialize["lt"] = o.Lt
	}
	if !IsNil(o.Lte) {
		toSerialize["lte"] = o.Lte
	}
	if !IsNil(o.TimeZone) {
		toSerialize["time_zone"] = o.TimeZone
	}
	return toSerialize, nil
}

type NullableMetaRangeQueryForSDK struct {
	value *MetaRangeQueryForSDK
	isSet bool
}

func (v NullableMetaRangeQueryForSDK) Get() *MetaRangeQueryForSDK {
	return v.value
}

func (v *NullableMetaRangeQueryForSDK) Set(val *MetaRangeQueryForSDK) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaRangeQueryForSDK) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaRangeQueryForSDK) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaRangeQueryForSDK(val *MetaRangeQueryForSDK) *NullableMetaRangeQueryForSDK {
	return &NullableMetaRangeQueryForSDK{value: val, isSet: true}
}

func (v NullableMetaRangeQueryForSDK) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaRangeQueryForSDK) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
